In [80]:
import numpy as np

In [81]:
num_movies=10
num_users=5
ratings = random.randint(11, size=(num_movies, num_users))

print (ratings) #We have a ratings matrix for 5 users giving ratings from 1 to 10 to 10 different movies.
#0 Indicates that the user has not rated a particular movie

[[ 9  3  2  3  8]
 [ 6  0  2 10  5]
 [ 7  6  1  4  7]
 [ 4  3  0  2  9]
 [ 8  8  7  7  1]
 [ 5  7  2  4  8]
 [ 7  6  1  4  6]
 [ 5  7  0  9  8]
 [10  7  2  3  9]
 [10  6  8  0  5]]


In [82]:
did_rate = (ratings != 0) * 1  #this matrix simply tells if the user has rated a particular movie or not
print(did_rate)

[[1 1 1 1 1]
 [1 0 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 0 1]]


In [83]:
priya_ratings = zeros((num_movies , 1))  #A matrix initially with 0 values (assuming that user hasnt rated yet) for
#a particular user with 10 rows for 10 movies
print (priya_ratings)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [84]:
#Here i am manually giving my ratings to the different movies in the list

priya_ratings[0] = 8
priya_ratings[4] = 7
priya_ratings[7] = 3

print(priya_ratings)


[[ 8.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 7.]
 [ 0.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 0.]]


In [85]:
ratings = append( (priya_ratings) ,ratings, axis=1)  #For user Priya, ratings matrix updated 
did_rate = append( ((priya_ratings !=0) *1) ,did_rate, axis=1) # and so did did_rate matrix


print(ratings)
print (did_rate)

[[  8.   9.   3.   2.   3.   8.]
 [  0.   6.   0.   2.  10.   5.]
 [  0.   7.   6.   1.   4.   7.]
 [  0.   4.   3.   0.   2.   9.]
 [  7.   8.   8.   7.   7.   1.]
 [  0.   5.   7.   2.   4.   8.]
 [  0.   7.   6.   1.   4.   6.]
 [  3.   5.   7.   0.   9.   8.]
 [  0.  10.   7.   2.   3.   9.]
 [  0.  10.   6.   8.   0.   5.]]
[[1 1 1 1 1 1]
 [0 1 0 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 0 1 1]
 [1 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [1 1 1 0 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 0 1]]


In [86]:
#We need to normalize our data before any machine learning alogrithm can be applied to it.
# In simple words, we take mean of our data set and subtract mean from each element of the data set (Mean Normalise)

#For example-

a = [10, 20 , 30]
avg = mean(a)
a = a - avg
a


array([-10.,   0.,  10.])

In [87]:
#function to normalize a dataset
 
def normalize_ratings(ratings , did_rate):            
    #args- ratings because we want to normalize it and did_rate because we want to normalize 
    #only those movies which have been rated(or simply that we dont wanna add or sub anything from the cells with 0 values)
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape = ((num_movies) ,1)) 
    #For storing later the mean of all the non-zero ratings for a particular movie
    
    ratings_norm = zeros(shape = (ratings.shape))
    #For storing the normalized version of the ratings matrix 

    for i in range(num_movies):
        #Get all the indices where rating is given
        idx = where(did_rate[i] == 1)[0]   
        #subscrpited 0 because where func returns a tuple and we need first element of the tuple which is an 
        #array of the indices of did rate hich statisfy a particular condition
        #Calculate the mean of the ith movie only for tha columns user has given a rating
        
        
        ratings_mean[i] = mean(ratings[i,idx]) #for non_zero ratings values i , j(idx) column 
        
        ratings_norm[i, idx] = ratings[i,idx] - ratings_mean[i]
        
    return ratings_norm , ratings_mean
        

In [88]:
ratings , ratings_mean = normalize_ratings( ratings , did_rate)

In [89]:
print (ratings)

[[ 2.5         3.5        -2.5        -3.5        -2.5         2.5       ]
 [ 0.          0.25        0.         -3.75        4.25       -0.75      ]
 [ 0.          2.          1.         -4.         -1.          2.        ]
 [ 0.         -0.5        -1.5         0.         -2.5         4.5       ]
 [ 0.66666667  1.66666667  1.66666667  0.66666667  0.66666667 -5.33333333]
 [ 0.         -0.2         1.8        -3.2        -1.2         2.8       ]
 [ 0.          2.2         1.2        -3.8        -0.8         1.2       ]
 [-3.4        -1.4         0.6         0.          2.6         1.6       ]
 [ 0.          3.8         0.8        -4.2        -3.2         2.8       ]
 [ 0.          2.75       -1.25        0.75        0.         -2.25      ]]


In [90]:
print (ratings_mean)

[[ 5.5       ]
 [ 5.75      ]
 [ 5.        ]
 [ 4.5       ]
 [ 6.33333333]
 [ 5.2       ]
 [ 4.8       ]
 [ 6.4       ]
 [ 6.2       ]
 [ 7.25      ]]


In [91]:
num_users = ratings.shape[1]

num_features = 3 
#Can be 100 - 1000 to depending upon regularization, variance , overfitting
# Feature here can be an action, comedy, romance
# Key here is that these features are shared by all the movies and all the users

In [92]:
movie_features = random.randn(num_movies , num_features)  
#We are genarating random numbers normally distributed as we dont have data sets 

user_prefs = random.randn(num_users , num_features) #Same as above

#For applying linear regression we need x and theta(parameters) 
initial_X_and_theta = r_[movie_features.T.flatten() , user_prefs.T.flatten()] 

This above is a code for the table where each movie will be given a number, like probabiblity of that movie of being "this fraction" comedy  , "this fraction" romance and "this fraction" action. Similarly for user preferences that how much a user like to watch different genre movies.

In [93]:
def unroll_parameters ( X_and_theta , num_users , num_movies , num_features):
    #Retrieving X and Theta from X_and_theta based on their dimensions
    #------------------------------------------------------------------------------------------
    
    #Get the first 30 rows and convert them into 10X3 matrix
    first_30 = X_and_theta[ : num_movies * num_features]  #Row slicing
    
    #We are extracting it exactly in the reverse way of how we created the x and theta combined matrix
    X = first_30.reshape((num_features, num_movies)).transpose() 
    
    #Get the rest 18 out of 48X1 matrix and reshape it
    
    last_18 = X_and_theta[num_movies * num_features : ] 
    
    theta = last_18.reshape((num_features , num_users)).transpose()
    
    return X, theta
    

In [94]:
def calculate_gradient (X_and_theta , ratings , did_rate , num_users , num_movies , num_features , reg_param):
    X, theta = unroll_parameters(X_and_theta , num_users  , num_movies , num_features)
    
    #We multiply by did_rate becasue we only want to consider observations where user has given some rating
    difference = X.dot(theta.T) * did_rate - ratings
    
    X_grad = difference.dot(theta) + reg_param * X
    theta_grad = difference.T.dot(X) + reg_param * theta
    
    #wrap all the gradients back into a column vector
    return r_[X_grad.T.flatten() , theta.T.flatten()]

In [95]:
def calculate_cost(X_and_theta , ratings , did_rate  , num_users , num_movies , num_features , reg_params):
    X , theta = unroll_parameters(X_and_theta , num_users , num_movies , num_features)
    
    #Again multiplied by did_rate because we want to consider only those params 
    
    cost = sum((X.dot(theta.T) * did_rate - ratings) **2 ) /2  # *did_rate means element-wise multiplication
    
    regularization = (reg_param / 2) * (sum(theta ** 2)) + sum(X ** 2)
    return cost+regularization
    
    

In [96]:
from scipy import optimize  #scipyt is used to minimized cost function using gradient descent
reg_param = 30


optimal_params_minimize_cost = optimize.fmin_cg(calculate_cost , fprime = calculate_gradient , x0=initial_X_and_theta , \
                            args = (ratings , did_rate , num_users , num_movies , num_features, reg_param), \
                            maxiter = 100 , disp = True , full_output = True)
#We have to provide fmin_cg function - Cost , gradient and args(self-explanatory), 
#maxiter is the number of decends we want to make. Means calculate_cost and calculate_gradient is called a 100 times


         Current function value: 153.466691
         Iterations: 7
         Function evaluations: 119
         Gradient evaluations: 107


In [97]:
#Extracting cost and features and parameters from the above returned value
optimal_movie_features_and_user_prefs  , cost = optimal_params_minimize_cost[0] , optimal_params_minimize_cost[1]  


In [101]:
movie_features , user_prefs = unroll_parameters(optimal_movie_features_and_user_prefs , num_users , num_movies , num_features)

In [102]:
print(movie_features) 

[[ -8.63695339e-05   2.13216221e-04  -2.49538373e-04]
 [  7.52107428e-04  -5.12036988e-04   1.49039486e-03]
 [ -4.77420471e-05   5.72069995e-04   4.19184336e-04]
 [ -1.20895561e-03  -3.07501344e-05  -9.62896145e-04]
 [ -1.32410119e-04  -6.57371091e-05   1.88597185e-04]
 [  9.22058739e-04  -4.19138250e-04   8.25897326e-04]
 [  4.90497577e-04   2.30788133e-05  -3.28153439e-04]
 [  3.34105029e-04  -1.44196232e-03   7.78293254e-04]
 [ -1.30358475e-03  -4.06178780e-04  -8.41298489e-04]
 [  5.38495461e-04  -4.52412497e-04   5.58767763e-04]]


In [110]:
all_predictions = movie_features.dot(user_prefs.T)  #Prediction matrix for ratings matrix

In [111]:
print(all_predictions) 
#We were not expecting these value for the ratings
#Ratings are provided 1 to 10 and integer values 
#We are getting these values because we normalized our ratings matrix

[[  9.20177617e-08  -5.34979115e-09   1.32123483e-07  -2.87693639e-08
    4.38147884e-08   2.90761943e-08]
 [ -5.18710470e-07  -1.63196805e-07  -4.83118694e-07   1.09778558e-07
   -2.82139895e-07  -8.98449453e-08]
 [  2.03285030e-08  -1.83242773e-07   1.08575003e-07  -5.91693424e-08
   -8.25514419e-08   1.62741388e-07]
 [  4.94509845e-07   2.56702356e-07   1.11850065e-07  -8.16668877e-08
    2.12338489e-07   1.56774308e-07]
 [ -9.15809255e-10   1.39447400e-09  -8.19677808e-08  -9.91904261e-10
   -2.81068421e-08   4.00713361e-08]
 [ -4.48869523e-07  -1.08235533e-07  -2.72880349e-07   1.07889888e-07
   -1.70938750e-07  -1.88804502e-07]
 [ -8.42921033e-08  -6.69585210e-09   1.31885445e-07   2.81512740e-08
    4.17504703e-08  -1.45184258e-07]
 [ -4.05633245e-07   1.86480852e-07  -6.96811413e-07   1.73173179e-07
   -1.25971962e-07  -2.45561176e-07]
 [  4.53608500e-07   3.33934415e-07  -6.63777430e-08  -4.89735623e-08
    2.00028560e-07   1.24613974e-07]
 [ -3.01146754e-07  -2.67941779e-08  

In [116]:
predictions_for_priya = all_predictions[: , 0:1] +ratings_mean

print(predictions_for_priya)

[[  9.20177614e-08]
 [ -5.18710470e-07]
 [  2.03285033e-08]
 [  4.94509846e-07]
 [ -9.15809650e-10]
 [ -4.48869523e-07]
 [ -8.42921031e-08]
 [ -4.05633245e-07]
 [  4.53608500e-07]
 [ -3.01146754e-07]]
